### PR TITLE
Switch to netmiko

### PR DESCRIPTION
**Pull request by mirceaulinic**
@fooelisa @dbarrosop @ktbyers

I think all of us agree that `pexpect` is already deprecated and proven to be an unreliable solution.
After a couple of months of using it, errors like #21 are not at all surprising anymore.
`The XML document is not well-formed` (https://github.com/fooelisa/pyiosxr/blob/master/pyIOSXR/iosxr.py#L36) also appears way too often, when the device actually does reply with a proper XML.

I am currently using this version and feels already like a massive improvement, although there's a major IOS-XR specific bug (reported, but without any interest for Cisco to fix it):

When issuing the CLI commands like:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<Request MajorVersion="1" MinorVersion="0">
<CLI><Configuration>show commit changes diff</Configuration></CLI>
</Request>
```

The XML agent crashes and exists from XML mode, after throwing the error:

```
XML> ERROR: 0x44318c06 'XML-TTY' detected the 'warning' condition 'A Light Weight Messaging library communication function returned an error': No such device or address
```

All we can do in such case is to re-enter in XML mode... If the device allows, of course.

@ktbyers I am using `send_command` instead of `send_command_expect` which does not seem suitable in this particular scenario.

### CODE REVIEW

**Comment by ktbyers** [comment]
@mirceaulinic I reviewed the Netmiko parts of this.

In the close() method, you can just call self.device.disconnect(). Nothing wrong with the way you did it, however. 

In Netmiko_1_0, send_command is going to become send_command_expect. There will be a separate send_command_timing() method. So we will need to fix this when Netmiko 1.0 is released (which won't be for a while).

What was the issue with using send_command_expect()? My concern is that send_command() does tend to be fragile i.e. when delays are meaningfully longer than expected things start to fail. In practice, send_command_expect() is more reliable (it will use the router prompt to determine that the command has completed). Of course, there could be some reason send_command_expect() doesn't work in this context...just didn't see it when looking through the code.

**Comment by mirceaulinic** [comment]
Hi @ktbyers thanks for looking at this.

The library consists basically on the following steps:
- open SSH connection
- send the command "xml" to enter in XML mode
- send XML requests and read XML reply

After entering in the XML mode, the prompt becomes "XML>".

Although I tried to call using

``` python
self.device.send_command_expect(command, expect_string='XML>', strip_prompt=False, strip_command=False, delay_factor=delay_factor)
```

It looks like it is waiting forever and never provides the output from the device. Is there anything I miss?

**Comment by mirceaulinic** [comment]
@ktbyers Also I noticed that huge replies are truncated. I am increasing now the value for `max_loops` to 1500. I will investigate if this brings any improvements.
However, my understanding is that `send_command_expect` should read till the line containing `XML>`. If that's the case indeed and will be able to make it work properly, I think that's the right method to use.

**Comment by ktbyers** [comment]
@mirceaulinic Let me start my IOS-XR device and test it.

**Comment by ktbyers** [comment]
@mirceaulinic Probably should make the expect pattern be a raw string.

```
expect_string=r'XML>'
```

Can you capture the manual output of an SSH session up through the entering XML> session?

Also what error do you get when using send_command_expect()?

Yes, the huge replies are truncated is an example of why I thought the send_command_expect() would be better to use.

**Comment by ktbyers** [comment]
FYI, I am trying to get my IOS-XRv device to start, but it might be having issues...

**Comment by mirceaulinic** [comment]
@ktbyers My bad, `send_command_expect` works as expected, just that I need to pay more attention to specify the `expect_string` properly when switching between contexts.
Thank you very much for your input!

I am pretty content with the current behaviour - it is not perfect but it is definitely a progress. With these said, I will proceed to adapt the tests.

**Comment by ktbyers** [comment]
@mirceaulinic FYI, it looks like you forgot to import NetMikoAuthenticationException. You use it later on.

```
from netmiko.ssh_exception import NetMikoTimeoutException, NetMikoAuthenticationException
```

**Comment by ktbyers** [comment]
@mirceaulinic FYI, I have my IOS-XRv up and running. It is running 5.3.1 code. I can also test against this if you have a set of tests.

**Comment by mirceaulinic** [comment]
@ktbyers 

> FYI, it looks like you forgot to import NetMikoAuthenticationException

Thanks, missed that!

I just wrote a couple of tests, some feedback would be much appreciated.

**Comment by mirceaulinic** [comment]
I finished writing the tests, I will wait for some more feedback from @ktbyers then I think we can merge this PR and release a new version.

**Comment by mirceaulinic** [comment]
Y'all IMO this pull request can be merged.
The code in here is already running in the production network for over a week and I can say it works just fine.
I tried to catch all the errors I've seen during the last couple of months, but I would not be surprised to see more :)
@ktbyers did you have any chance to test it a bit?

**Comment by ktbyers** [comment]
@mirceaulinic No, I didn't get a chance to test it. 

I did look through the code earlier and I thought it was fine for the Netmiko parts. I will probably try to test in the next few weeks, but I am fine with PR being accepted.

**Comment by mirceaulinic** [comment]
@fooelisa could you please release pyiosxr 0.20?

**Pull request merged**
