### PR TITLE
Lock/Unlock on demand

### PR DESCRIPTION
**Pull request by mirceaulinic**
There is a need for long standing sessions to lock the config DB only when needed. For example if one starts the script as a daemon, while the process will run in background no other user would be allowed to make changes to the config of the device.
This is why we propose to lock the config only when needed.

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Solution proposed does not change at all the current behavior. But in case one would like to not have the session locked by default, would simply instantiate the object using the argument `lock = False` and call the `lock()` & `unlock()` methods when needed.

**Comment by jejenone** [comment]
+1 on this.

**Comment by jejenone** [comment]
@fooelisa comments ? thoughts ?

**Comment by fooelisa** [comment]
yep! sorry for the delay, just got back from a long trip yesterday. I'll need to re-do some napalm functionality to go along with this, give me a day or two

**Comment by fooelisa** [comment]
Oh now I see that you are not actually changing the current behavior :) I'll propagate this into napalm (along the lines of the junos PR you sent). Thanks!

**Pull request merged**
