### PR TITLE
fixed issue with netmiko_kwargs

### PR DESCRIPTION
**Pull request by thorko**
there was an issue when opening the connection to the device.
Please check and merge my pull request.

### CODE REVIEW

**Comment by starthir** [comment]
Hi,

We came to the same fix regarding https://github.com/fooelisa/pyiosxr/pull/48/commits/7e153191484b521a0f8ca0aef5f23edd974f2273

Regarding the second commit, that didn't work for us (actually works without it):
https://github.com/fooelisa/pyiosxr/pull/48/commits/313b1f7bf270c2a0be3afc28bb367bae4e3e3674

Thanks for the awesome work with NAPALM!

**Comment by thorko** [comment]
Yeah, we tested the second commit also in our production environment, but it didn't work. The cisco support told us to do so. We've asked cisco support why "show configuration merge" doesn't work in Exec environment and what to use instead.
Our xml agent at an iosxr router gets repeatedly stuck and we've opened a cisco case. We'll see what they recommend.

**Review by mirceaulinic — APPROVED** [review]

**Comment by mirceaulinic** [comment]
For some reason, I don't receive notifications from this repo.
Thanks, @thorko and apologize again for the late reply.

**Comment by thorko** [comment]
@mirceaulinic no big deal. I'm glad I could help

_Sent from my Samsung GT-I8190 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request merged**
